'use client';
import { useState, useEffect, use } from 'react';
import { supabase } from '@/lib/supabase';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Calendar, Phone, Activity, Clock, Edit, FileText, Plus, X, Download, Send } from 'lucide-react';
import MedicalDocuments from '@/components/MedicalDocuments';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { motion, AnimatePresence } from 'framer-motion';
import { uploadPatientDocument } from '@/lib/patientDocuments';

export default function PatientDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const router = useRouter();
  const { id } = use(params);
  const [patient, setPatient] = useState<any>(null);
  const [appointments, setAppointments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Prescription Modal State
  const [isPrescriptionModalOpen, setIsPrescriptionModalOpen] = useState(false);
  const [activeAppointment, setActiveAppointment] = useState<any>(null);
  const [medicines, setMedicines] = useState<{name: string, dosage: string, frequency: string, duration: string}[]>([]);
  const [newMedicine, setNewMedicine] = useState({name: '', dosage: '', frequency: '', duration: ''});
  const [prescriptionNotes, setPrescriptionNotes] = useState('');
  const [refreshKey, setRefreshKey] = useState(0);

  useEffect(() => {
    if (id) {
      fetchPatientDetails();
    }
  }, [id]);

  async function fetchPatientDetails() {
    try {
      // Fetch Patient
      const { data: pData, error: pError } = await supabase
        .from('patients')
        .select('*')
        .eq('id', id)
        .single();
      
      if (pError) throw pError;
      setPatient(pData);

      // Fetch Appointments
      const { data: aData, error: aError } = await supabase
        .from('appointments')
        .select('*')
        .eq('patient_id', id)
        .order('appointment_date', { ascending: false });
      
      if (aError) throw aError;
      setAppointments(aData || []);

    } catch (err) {
      console.error('Error fetching patient details:', err);
    } finally {
      setLoading(false);
    }
  }

  const handleAddMedicine = () => {
    if (newMedicine.name && newMedicine.dosage) {
      setMedicines([...medicines, newMedicine]);
      setNewMedicine({name: '', dosage: '', frequency: '', duration: ''});
    }
  };

  const generatePrescriptionPDF = async () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(24);
    doc.setTextColor(124, 58, 237); // Violet-600
    doc.text('ClinicOS', 14, 25);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Smart Medical Management', 14, 32);
    doc.setFontSize(10);
    doc.setTextColor(30);
    doc.text('KK Neuro Vision Therapy Institute', 140, 20);
    doc.text('Dr. Vikash & Team', 140, 26);
    
    // Patient Info
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text('Medical Prescription', 14, 50);
    doc.setFontSize(10);
    doc.text(`Patient: ${patient.name}`, 14, 60);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 140, 60);

    // Medicines Table
    const tableData = medicines.map(m => [m.name, m.dosage, m.frequency, m.duration]);
    (doc as any).autoTable({
      startY: 70,
      head: [['Medicine', 'Dosage', 'Frequency', 'Duration']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [124, 58, 237] }
    });

    // Notes
    if (prescriptionNotes) {
      const finalY = (doc as any).lastAutoTable.finalY || 70;
      doc.text('Doctor Notes:', 14, finalY + 15);
      doc.text(prescriptionNotes, 14, finalY + 22, { maxWidth: 180 });
    }

    // Save
    const filename = `Prescription_${patient.name.replace(/\s+/g, '_')}.pdf`;
    doc.save(filename);

    // Silently upload to Supabase medical_records
    try {
      const pdfBlob = doc.output('blob');
      const pdfFile = new File([pdfBlob], filename, { type: 'application/pdf' });
      const { doc: uploadedDoc, error } = await uploadPatientDocument(id, pdfFile);
      if (error) {
        console.error('Error uploading prescription PDF:', error);
      } else if (uploadedDoc) {
        setRefreshKey(prev => prev + 1);
      }
    } catch (uploadErr) {
      console.error('Failed to auto-upload prescription PDF:', uploadErr);
    }
  };

  const sendPrescriptionWhatsApp = async () => {
    if (!patient.phone) {
      alert("No phone number on file.");
      return;
    }
    
    try {
      const medList = medicines.map(m => `- ${m.name} (${m.dosage}) ${m.frequency}`).join('\n');
      const message = `Hello ${patient.name}! 🙏\n\nYour prescription has been generated by Dr. Vikash at *KK Neuro Vision Therapy Institute*.\n\n*Medicines:*\n${medList}\n\n*Notes:*\n${prescriptionNotes}\n\nGet well soon!\n- KK Neuro Vision Therapy Institute`;
      const cleanPhone = patient.phone.replace(/[^0-9]/g, '');
      const formattedPhone = cleanPhone.length === 10 ? `91${cleanPhone}` : cleanPhone;
      
      const res = await fetch('http://localhost:8081/message/sendText/ClinicBot1', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'apikey': 'yaot6e7yab8rlcxl95uw' },
        body: JSON.stringify({
          number: formattedPhone,
          text: message
        })
      });

      if (res.ok) {
        alert("✅ Prescription sent via WhatsApp!");
      } else {
        window.open(`https://wa.me/${formattedPhone}?text=${encodeURIComponent(message)}`, '_blank');
      }
    } catch (e) {
      console.error(e);
      const cleanPhone = patient.phone.replace(/[^0-9]/g, '');
      const formattedPhone = cleanPhone.length === 10 ? `91${cleanPhone}` : cleanPhone;
      const medList = medicines.map(m => `- ${m.name} (${m.dosage}) ${m.frequency}`).join('\n');
      const message = `Hello ${patient.name}! 🙏\n\nYour prescription has been generated by Dr. Vikash at *KK Neuro Vision Therapy Institute*.\n\n*Medicines:*\n${medList}\n\n*Notes:*\n${prescriptionNotes}\n\nGet well soon!\n- KK Neuro Vision Therapy Institute`;
      window.open(`https://wa.me/${formattedPhone}?text=${encodeURIComponent(message)}`, '_blank');
    }
  };

  if (loading) {
    return <div className="p-20 text-center text-slate-400 font-bold">Loading patient records...</div>;
  }

  if (!patient) {
    return (
      <div className="p-20 text-center">
        <h2 className="text-2xl font-bold text-slate-900 mb-4">Patient Not Found</h2>
        <button onClick={() => router.back()} className="btn-primary">Go Back</button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <button onClick={() => router.back()} className="flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-900 transition-colors">
        <ArrowLeft size={16} />
        Back to Patients
      </button>

      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight mb-2 text-slate-900">{patient.name}</h1>
          <div className="flex items-center gap-4 text-sm font-medium text-slate-500">
            <span className="flex items-center gap-1"><Phone size={14} /> {patient.phone}</span>
            <span className="flex items-center gap-1"><Calendar size={14} /> Registered: {new Date(patient.created_at).toLocaleDateString()}</span>
          </div>
        </div>
        <button className="flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl font-bold transition-all border border-slate-200 bg-white text-slate-700 hover:bg-slate-50">
          <Edit size={16} />
          Edit Profile
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-1 space-y-6">
          <div className="clinic-card p-6">
            <h3 className="text-sm font-bold text-slate-900 mb-4 uppercase tracking-wider">Patient Overview</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between p-3 rounded-xl bg-slate-50">
                <div className="flex items-center gap-3">
                  <Activity size={18} className="text-blue-500" />
                  <span className="font-bold text-slate-700">Total Visits</span>
                </div>
                <span className="font-black text-slate-900">{appointments.length}</span>
              </div>
              <div className="flex items-center justify-between p-3 rounded-xl bg-slate-50">
                <div className="flex items-center gap-3">
                  <Clock size={18} className="text-emerald-500" />
                  <span className="font-bold text-slate-700">Last Visit</span>
                </div>
                <span className="font-bold text-slate-900">
                  {appointments.length > 0 ? new Date(appointments[0].appointment_date).toLocaleDateString() : 'Never'}
                </span>
              </div>
            </div>
          </div>
        </div>

        <div className="md:col-span-2">
          <div className="clinic-card p-6">
            <h3 className="text-sm font-bold text-slate-900 mb-6 uppercase tracking-wider">Appointment History</h3>
            
            {appointments.length === 0 ? (
              <div className="text-center py-10">
                <div className="w-12 h-12 rounded-full bg-slate-50 flex items-center justify-center mx-auto mb-3">
                  <Calendar size={20} className="text-slate-400" />
                </div>
                <p className="text-slate-500 font-medium">No appointments found.</p>
              </div>
            ) : (
              <div className="space-y-4">
                {appointments.map((apt) => (
                  <div key={apt.id} className="flex flex-col md:flex-row md:items-center justify-between p-4 rounded-xl border border-slate-100 bg-slate-50 hover:border-slate-200 transition-colors">
                    <div>
                      <p className="font-bold text-slate-900 mb-1">{new Date(apt.appointment_date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
                      <p className="text-xs font-medium text-slate-500">{apt.notes || 'Routine Checkup'}</p>
                    </div>
                    <div className="flex items-center gap-4 mt-3 md:mt-0">
                      <span className="font-bold text-slate-700">{apt.appointment_time}</span>
                      <span className={`px-3 py-1 text-xs font-bold uppercase tracking-wider rounded-md ${
                        apt.status === 'completed' ? 'bg-emerald-100 text-emerald-700' :
                        apt.status === 'confirmed' ? 'bg-blue-100 text-blue-700' :
                        'bg-slate-200 text-slate-600'
                      }`}>
                        {apt.status}
                      </span>
                      <button onClick={() => { setActiveAppointment(apt); setIsPrescriptionModalOpen(true); }} className="ml-2 px-3 py-1 text-xs font-bold uppercase tracking-wider rounded-md bg-purple-100 text-purple-700 hover:bg-purple-200 transition-colors flex items-center gap-1">
                        <Plus size={12} />
                        Rx
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ─── Medical Documents & Reports ─── */}
      <div className="clinic-card p-6">
        <h3 className="text-sm font-bold text-slate-900 mb-4 uppercase tracking-wider">Medical Documents & Reports</h3>
        <MedicalDocuments patientId={id} key={refreshKey} />
      </div>

      <AnimatePresence>
        {isPrescriptionModalOpen && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }} className="bg-white rounded-3xl shadow-2xl w-full max-w-2xl overflow-hidden flex flex-col max-h-[90vh]">
              <div className="p-6 border-b border-slate-100 flex items-center justify-between bg-slate-50">
                <div>
                  <h2 className="text-xl font-extrabold text-slate-900">New Prescription</h2>
                  <p className="text-sm font-medium text-slate-500">For {patient?.name}</p>
                </div>
                <button onClick={() => setIsPrescriptionModalOpen(false)} className="w-8 h-8 rounded-full bg-white border border-slate-200 flex items-center justify-center text-slate-500 hover:text-slate-900 hover:bg-slate-100 transition-colors">
                  <X size={18} />
                </button>
              </div>
              
              <div className="p-6 overflow-y-auto flex-1 space-y-6">
                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">Add Medicine</label>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
                    <input type="text" placeholder="Medicine Name" className="col-span-2 md:col-span-1 p-3 rounded-xl border border-slate-200 text-sm font-medium focus:border-purple-500 outline-none" value={newMedicine.name} onChange={e => setNewMedicine({...newMedicine, name: e.target.value})} />
                    <input type="text" placeholder="Dosage (e.g. 500mg)" className="p-3 rounded-xl border border-slate-200 text-sm font-medium focus:border-purple-500 outline-none" value={newMedicine.dosage} onChange={e => setNewMedicine({...newMedicine, dosage: e.target.value})} />
                    <input type="text" placeholder="Freq (e.g. 1-0-1)" className="p-3 rounded-xl border border-slate-200 text-sm font-medium focus:border-purple-500 outline-none" value={newMedicine.frequency} onChange={e => setNewMedicine({...newMedicine, frequency: e.target.value})} />
                    <input type="text" placeholder="Duration (e.g. 5 Days)" className="p-3 rounded-xl border border-slate-200 text-sm font-medium focus:border-purple-500 outline-none" value={newMedicine.duration} onChange={e => setNewMedicine({...newMedicine, duration: e.target.value})} />
                  </div>
                  <button onClick={handleAddMedicine} className="w-full py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-sm font-bold transition-colors">Add to Prescription</button>
                </div>

                {medicines.length > 0 && (
                  <div className="border border-slate-200 rounded-xl overflow-hidden">
                    <div className="bg-slate-50 px-4 py-2 border-b border-slate-200 grid grid-cols-4 text-xs font-bold text-slate-500 uppercase tracking-wider">
                      <span>Medicine</span><span>Dosage</span><span>Freq</span><span>Duration</span>
                    </div>
                    {medicines.map((m, i) => (
                      <div key={i} className="px-4 py-3 border-b last:border-b-0 border-slate-100 grid grid-cols-4 text-sm font-medium text-slate-900">
                        <span>{m.name}</span><span>{m.dosage}</span><span>{m.frequency}</span><span>{m.duration}</span>
                      </div>
                    ))}
                  </div>
                )}

                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">Doctor's Notes / Advice</label>
                  <textarea rows={3} className="w-full p-4 rounded-xl border border-slate-200 text-sm font-medium focus:border-purple-500 outline-none resize-none" placeholder="Any special instructions..." value={prescriptionNotes} onChange={e => setPrescriptionNotes(e.target.value)}></textarea>
                </div>
              </div>

              <div className="p-6 border-t border-slate-100 bg-slate-50 flex items-center justify-between">
                <button onClick={() => setIsPrescriptionModalOpen(false)} className="px-6 py-2.5 rounded-xl font-bold text-slate-500 hover:bg-slate-200 transition-colors">Cancel</button>
                <div className="flex gap-3">
                  <button onClick={generatePrescriptionPDF} className="px-6 py-2.5 rounded-xl font-bold bg-slate-900 text-white hover:bg-slate-800 transition-colors flex items-center gap-2">
                    <Download size={16} /> Save PDF
                  </button>
                  <button onClick={sendPrescriptionWhatsApp} className="px-6 py-2.5 rounded-xl font-bold bg-green-500 text-white hover:bg-green-600 transition-colors flex items-center gap-2">
                    <Send size={16} /> WhatsApp
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
